import { StyleSheet } from 'react-native';

export const Styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffffff',
  },
  content: {
    backgroundColor: '#FFE7E7',
    marginBottom: -50,
  },
  box: {
    width: 200,
    height: 200,
    borderWidth: 1,
  },
  boxconfs: {
    gap: 10,
    marginTop: 20,
  },
  textconf: {
    flex: 1,
    marginTop: 30,
    fontSize: 35,
    marginLeft: 20,
    color: '#B41513',
  },
  logo: {
    width: 144,
    height: 144,
    marginBottom: 46,
  },
  header: {
    width: '100%',
    height: 100,
    flex:1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  header2: {
    backgroundColor: '#fff',
    height: '35%',
    marginLeft: 20,
    borderRadius: 50,
    flex: 1,
    alignContent: 'flex-start',
    justifyContent: 'center',
    marginRight: 10,
  },
  textheader2: {
    marginLeft: 20,
  },
  profile:{
    backgroundColor: '#fff',
    borderRadius: 50,
    width:80,
    height:80,
    alignItems:'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  title: {
    color: "#B41513",
    fontSize: 35,
    textAlign: "center",
    marginBottom: 60,
    width: 300,
  },
  subtitle: {
    fontSize: 16,
    color: '#555',
    marginBottom: 30,
    textAlign: 'center',
  },
  info: {
    backgroundColor: '#fff',
    marginBottom: 10,
    marginLeft: 20,
    marginRight: 20,
    borderRadius: 25,
    height: 35,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  gear: {
    backgroundColor: '#fff',
    width: 50,
    flex: 1,
    alignItems: 'center',
    borderRadius: 10,
  },
  backButton: {
    position: 'absolute',
    top: 10,
    left: 300,
    zIndex: 10,
    marginTop: 30,
  },
  titlemid: {
    color: "#9d9d9dff",
    fontSize: 15,
    textAlign: "center",
  },
  buttonContainer: {
    flexDirection: 'row',
    gap: 20,
    paddingHorizontal: 100,
    padding: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {
    backgroundColor: '#FFF',
    paddingVertical: 12,
    paddingHorizontal: 40,
    borderRadius: 25,
    marginTop: 10,
  },
  buttonText: {
    color: '#B41513',
    fontSize: 20,
    fontWeight: '600',
  },
  buttoncadastro: {
    backgroundColor: "#FFFFFF",
    borderRadius: 25,
    padding: 11,
  },
});